### ISSUE TITLE
Missing sqlite integration plugin?

### ISSUE THREAD

**Issue by codecowboy** [sandstormports/wordpress#3]
There is a symlink here to a read-only plugins folder. Are there some plugins missing from this repo which are required for the sandstorm port to work? Is the sqlite integration sandstorm-specific?

https://github.com/sandstormports/wordpress/blob/master/wp-content/plugins/sqlite-integration

I realise this is old - I am evaluating how much work is involved in getting this working and bumping the WordPress version. As discussed with and witnessed by @JamborJan today, the app is not installable as it is. I am aware there is a separate package repo.

It could be that it would be easier to begin a new port rather than try to figure out how it was done originally as it has already involved a fair amount of yak-shaving ;)

@dwrensha @ocdtrekkie

**Comment by ocdtrekkie** [comment]
It's here: https://github.com/sandstormports/wordpress-sandstorm/tree/master/read-only-plugins/sqlite-integration

Here's the WordPress link, but it looks like it may have been removed: https://wordpress.org/plugins/sqlite-integration/

--
 Jacob Weisz
 inbox@jacobweisz.com

**Comment by codecowboy** [comment]
Sorry, yes. I realised it’s in the other repo. There is also a sandstorm plugin which is handling the auto login. It is starting to make a bit more sense now.
